# For more information, see:
# https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5,
# nightly-2015-09-21, ghc-7.10.2)
resolver: lts-3.6

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- docopt-0.7.0.4
# - readline-1.0.3.0

# Override default flag values for local packages and extra-deps
flags:

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Extra directories used by stack for building
# extra-include-dirs: [/usr/local/Cellar/readline/6.3.8/include]
# extra-lib-dirs:     [/usr/local/Cellar/readline/6.3.8/lib]

# ghc-options:
#   readline:                                                          \
#     --with-readline-includes /usr/local/Cellar/readline/6.3.8/include \
#     --with-readline-lib /usr/local/Cellar/readline/6.3.8/lib